### ISSUE TITLE
Merge Error for cosmoshub chain

### ISSUE THREAD

**Issue by pmorrow90** [elsehow/tendermint-tax#8]
Getting the following error

> (venv) ➜  tendermint-tax git:(main) ✗ python3 tendermint-tax.py --chain cosmoshub --address [cosmoshubaddress] --ticker ATOM --fystart "2021-01-01" --fyend "2021-12-31" --outfile "cosmos.csv" -v
> 2022-02-28 14:40:41 INFO: Querying RPC for transfer.recipient='[cosmoshubaddress]'
> 2022-02-28 14:40:42 INFO: Computing inflows and outflows for [cosmoshubaddress]
> 2022-02-28 14:40:42 INFO: Querying RPC for the UTC time of each relevant block height
> 2022-02-28 14:40:42 INFO: Querying historical pricing data on ATOM
> 2022-02-28 14:40:48 INFO: Computing historical fair market value (FMV) for ATOM
> 2022-02-28 14:40:48 INFO: Aligning blocks with historical pricing data
> Traceback (most recent call last):
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/tendermint-tax.py", line 101, in <module>
>     merged_df = pd.merge_asof(inflow_outflow_df, fmvs_df, on='time', direction='nearest')
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 580, in merge_asof
>     op = _AsOfMerge(
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1740, in __init__
>     _OrderedMerge.__init__(
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1623, in __init__
>     _MergeOperation.__init__(
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
>     ) = self._get_merge_keys()
>   File "/Users/zinc-ops/Documents/GitHub/tendermint-tax/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1858, in _get_merge_keys
>     raise MergeError(msg)
> pandas.errors.MergeError: incompatible merge keys [0] dtype('<M8[ns]') and datetime64[ns, UTC], must be the same type

**Comment by elsehow** [comment]
I cannot replicate this error without knowing your Cosmos address. Please try with a new Cosmos address or provide the Cosmos address that causes the error.
